### ISSUE TITLE
GTK+ errors thrown when running a GTK3 application from command line or deve environment

### ISSUE THREAD

**Issue by fmeloni** [LinxGem33/OSX-Arc-Plus#2]
(Otro:14860): Gtk-WARNING **: Theme parsing error: gtk.css:4101:29: Expected ',' in color definition

(Otro:14860): Gtk-WARNING **: Theme parsing error: gtk.css:4142:92: The :prelight pseudo-class is deprecated. Use :hover instead.

(Otro:14860): Gtk-WARNING **: Theme parsing error: gtk.css:4146:43: The :prelight pseudo-class is deprecated. Use :hover instead.

**Comment by LinxGem33** [comment]
@fmeloni 

appreciate the feed back, This error indicates that the software is using valid GTK library calls with a newer version of the GTK library. Sometimes during software development it is desirable to get rid of the, "old way", to do things while maintaining backwards compatibility. This is accomplished by marking the undesired calls deprecated. This tells the developer that their code is valid in this release, but in the future their code will need to be updated to work with a new version of the library, possibly many releases down the road. 

Also because this theme is heavily based on the pixmap engine, a lot of the styling comes from the images, regarding this issue it could also be a bug in Orion as its currently unmaintained and needs serious updates for Gtk3.

please see [bug #1392669](https://bugs.launchpad.net/ubuntu/+source/shimmer-themes/+bug/1392669)

kind regards

**Comment by fmeloni** [comment]
I get perfectly what you explain (20+ years of IT here, heheh)

The curious thing is that with your other three themes everything goes smoothly and I get no warnings or errors at all, everything pretty clean.

BTW, I can't deal with myself and made two VLC skins, LOL. I will upload them to Dropbox later and let you download them.

**Comment by LinxGem33** [comment]
@fmeloni 

hence why this theme is currently in beta till the changes are frozen and the code can be rendered stable enough for release.

kind regards

**Comment by roachsinai** [comment]
Hi, Is OSX-Arc-Plus still beta? cause I also have this problem...
