### ISSUE TITLE
Gtk-WARNING **: Theme parsing error

### ISSUE THREAD

**Issue by simonbcn** [LinxGem33/OSX-Arc-Plus#5]
```
(gnome-screenshot:10777): Gtk-WARNING **: Theme parsing error: gtk.css:4101:29: Expected ',' in color definition

(gnome-screenshot:10777): Gtk-WARNING **: Theme parsing error: gtk.css:4142:92: The :prelight pseudo-class is deprecated. Use :hover instead.

(gnome-screenshot:10777): Gtk-WARNING **: Theme parsing error: gtk.css:4146:43: The :prelight pseudo-class is deprecated. Use :hover instead.
```

**Comment by LinxGem33** [comment]
@simonbcn 

what’s yours OS distro etc...

appreciate the feed back, This error indicates that the software is using valid GTK library calls with a newer version of the GTK library. Sometimes during software development it is desirable to get rid of the, "old way", to do things while maintaining backwards compatibility. This is accomplished by marking the undesired calls deprecated. This tells the developer that their code is valid in this release, but in the future their code will need to be updated to work with a new version of the library, possibly many releases down the road.

Also because this theme is heavily based on the pixmap engine, a lot of the styling comes from the images, regarding this issue it could also be a bug in Orion as its currently unmaintained and needs serious updates for Gtk3.

kind regards

**Comment by simonbcn** [comment]
Arch Linux

**Comment by LinxGem33** [comment]
gtk version and OS version.

kind regards

**Comment by annesylvie** [comment]
Hi,
I also use the Arc Plus Gnome theme on Arch Linux (and love it!). I got the same errors when I was running dconf-editor. While everything works perfectly, I figured I could let you know for future updates.
I am using gtk3 version 3.22.15-1, and running Arch with the 4.11.3-1 linux kernel.

**Comment by LinxGem33** [comment]
@annesylvie 

appreciate the feed back, i have removed this theme for further development as i was using depreciated code and it needs updating hence why it was throwing errors hopefully i can have it working for a future release.

kind regards
